### ISSUE TITLE
High tx rate floods pending queue on loaded node (node 1, running benchmark)

### ISSUE THREAD

**Issue by sitano** [Consensys-Incorporated/quorum#111]
#### System information

Geth version: `geth version` = `1.5.0-unstable-e3a0ae27`

OS & Version: Windows/Linux/OSX = `Ubuntu 16.04.2 LTS / 4.4.0-1013-aws`

Branch, Commit Hash or Release: `git status` = master / e3a0ae27

#### Expected behaviour

I run https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/bench-public-sync.sh 100 tx/s 1 thread 5 minutes and expect it to work fine. I expect imported blocks to contain processed txs, or txs being rejected and system to proceed fine. 

#### Actual behaviour

First block after start contains ~22 txs.
Second ~1500 txs.
Third ~2500 txs.
All following ~3 txs (voting).

Even though I can believe txs being rejected due to the being duplicates, exceeding limits, the main problem is with the 1 node to which the load (txs) was sent. It grows its pending queue.

The overall behavior does not look like something consistent. Transactions start to exceed maxPendingTotal (tx_tool.go/promoteExecutables). At first they've got successfully promoted. Then other nodes successfully starts to drop the pending queue tail due to the successfully evaluating spammer / offender address (tx_tool.go/promoteExecutables), which is not the case for the first node. The first node does not do that (because all txs are local to it). Then block maker commits what it have (~4k txs), and starts to reject txs due to the per account queue limit (16). Why it did not do that before? 

Anyway, first node on which the load is pushed stays with this uncommitted pending queue and it just grows doing nothing.

Sometimes node starts to report tx errors on preCheck() about invalid nonce. 

Then this first node mostly can't process txs any further, and number of pending txs queue start to grow.

#### Steps to reproduce the behaviour

Follow steps at https://github.com/jpmorganchase/quorum-examples/ to init and start the system.

$ ./bench-public-sync.sh 100 2m 1

Then check logs with `grep imported qdata/logs/1.log`, look for something like:
```
I0505 11:30:44.908226 core/blockchain.go:1069] imported 1 blocks,     5 txs (  0.201 Mg) in   4.672ms (42.926 Mg/s). #1 [27e08aa3…]
I0505 11:30:50.910432 core/blockchain.go:1069] imported 1 blocks,     3 txs (  0.155 Mg) in   3.800ms (40.653 Mg/s). #2 [e58238c5…]
I0505 11:30:54.929299 core/blockchain.go:1069] imported 1 blocks,    22 txs (  0.599 Mg) in  15.477ms (38.700 Mg/s). #3 [bb3e5fb8…]
I0505 11:31:00.121062 core/blockchain.go:1069] imported 1 blocks,  1515 txs ( 36.122 Mg) in 911.455ms (39.631 Mg/s). #4 [a1c29d78…]
I0505 11:31:07.644201 core/blockchain.go:1069] imported 1 blocks,  2584 txs ( 61.551 Mg) in    1.087s (56.597 Mg/s). #5 [8d5f1fd7…]
I0505 11:31:12.538759 core/blockchain.go:1069] imported 1 blocks,     2 txs (  0.123 Mg) in   3.281ms (37.508 Mg/s). #6 [60dc570d…]
I0505 11:31:16.537383 core/blockchain.go:1069] imported 1 blocks,     2 txs (  0.123 Mg) in   4.775ms (25.801 Mg/s). #7 [bfb911c5…]
I0505 11:31:22.544465 core/blockchain.go:1069] imported 1 blocks,     2 txs (  0.123 Mg) in   3.915ms (31.474 Mg/s). #8 [e049af9b…]
```

Then connect to the first node:

$ geth attach ipc:qdata/dd1/geth.ipc
> eth.getPendingTransactions() -> > 20k txs and growing

**Comment by sitano** [comment]
I can provide you with the logs, ansible script for AWS, or anything if needed. For now, I invested 2 days  looking into the code trying to understand an issue, and the cause does look obvious to me.

**Comment by tylobban** [comment]
Hi @sitano, please post the output from the benchmark script. Also, what do you have the blockmaker configured for in terms of block time?

**Comment by sitano** [comment]
Hi @tylobban , blockmaker configured as in the default 7nodes examples repository:

    PRIVATE_CONFIG=tm2.conf nohup geth --datadir qdata/dd2 $GLOBAL_ARGS --rpcport 22001 --port 21001 --voteaccount "0x0fbdc686b912d7722dc86510934589e0aaf3b55a" --votepassword "" --blockmakeraccount "0xca843569e3427144cead5e4d5999a3d0ccf92b8e" --blockmakerpassword "" --singleblockmaker --minblocktime 2 --maxblocktime 5

[wrk-test-pending-failed.tar.gz](https://github.com/jpmorganchase/quorum/files/1001526/wrk-test-pending-failed.tar.gz)

**Comment by sitano** [comment]
I have tried various parameters for wrk2 (https://github.com/giltene/wrk2), it seems like the issue happens under a specific level of pressure. For 1 thread / 1 connection it starts near ~280 reqs/s:

` ~/wrk2 -s ~/7nodes/send-public-sync.lua -c 1 -d 10m -t 1 -R 280 -L http://localhost:22000/`

After blockmaker detects 1 spammer, it cuts a tail of the pending queue, commits what it have and then the first node stops publishing its pending txs to the blockmaker...

The easiest way to reproduce the case is to use default script `bench-public-sync.sh` getting up to 3K txs.

**Comment by tylobban** [comment]
Yes so as you point out the local node is programmed so that it doesn’t drop any transaction from the local client and hence all the transactions are stuck in the pending queue. Initially, the node behaves properly and all the other nodes expect to synchronize with it but once it starts overloading the network, it gets marked as a spammer and fails to synchronize with any of the other nodes. Once the node is overloaded with pending transactions, it has to be restarted to clean up pending queue.
 
You can bypass this by queuing transactions before sending them to the node. 

Having said that, we do think the standard ethereum p2p protocol here is not directly relevant to a permissioned chain configuration, and so we are looking to make enhancements to this as part of the roadmap.  Feel free to reach out if you would like to work on this and submit a pull request!

**Comment by sitano** [comment]
@tylobban got it. thx. 

Do you have any intent of pushing forward transition to the geth 1.6? (I saw merged branch there merged with conflicts). Maybe ETH guys changed something in their p2p transport limits handling already... Need to try.

**Comment by tylobban** [comment]
@sitano indeed, work to upgrade to 1.6 is on going!

**Comment by patrickmn** [comment]
This issue should be fixed as of Quorum 2.0.0. Please let us know if that's not the case.

**Comment by realcodywburns** [comment]
this is still an issue using Quorum 2.0.0 running ibft. Same behavior.

geth version: 1.7.2-stable-ee498061

In longer tests, the node fails eventually completely with the error log filled with 
`IPC accept failed: accept unix /7nodes/qdata/dd1/geth.ipc: accept4: too many open files`

The issue is that geth is not closing connections it cannot respond to so the number of connections eventually becomes unmanageable 

```
lsof | grep 10.0.0.4:8545 | wc -l
27705 connections waiting to close
```
