### ISSUE TITLE
Makefile fails to build the project with Go 1.8

### ISSUE THREAD

**Issue by coeniebeyers** [Consensys-Incorporated/quorum#69]
#### System information

Geth version: `geth version`
Version: 1.5.9-stable
Git Commit: a07539fb88db7231d18db918ed7a6a4e32f97450
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: linux
GOPATH=
GOROOT=/usr/lib/go-1.7

OS & Version: Windows/Linux/OSX
Ubuntu 14.04

Branch, Commit Hash or Release: `git status`
On branch master, commit e6282c280b578a5d75d9e31ba5294732c9752356

Update:
$go version
go version go1.8 linux/amd64

#### Expected behaviour
git clone https://github.com/jpmorganchase/quorum.git
cd quorum
make all
make test

#### Actual behaviour
git clone https://github.com/jpmorganchase/quorum.git
cd quorum
make all
build/env.sh go run build/ci.go install
unexpected directory layout:
	import path: _/home/coenie/workspace/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/build
	root: /home/coenie/workspace/quorum/build/_workspace/src
	dir: /home/coenie/workspace/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/build
	expand root: /home/coenie/workspace/quorum/build/_workspace/src
	expand dir: /home/coenie/workspace/quorum/internal/build
	separator: /
make: *** [all] Error 1

#### Steps to reproduce the behaviour
make all

#### Backtrace

````
[backtrace]
````

**Comment by patrickmn** [comment]
**Edit for bump: You can use the native Go tooling by checking out Quorum as github.com/ethereum/go-ethereum as a workaround for now:**


```bash
cd
mkdir -p go/src/github.com/ethereum
cd go/src/github.com/ethereum
git clone https://github.com/jpmorganchase/quorum go-ethereum
export GOPATH=~/go
go get github.com/ethereum/go-ethereum/cmd/geth
cd ~/go/bin
./geth version
```

Output:

```bash
localhost ~: cd
localhost ~: mkdir -p go/src/github.com/ethereum
localhost ~: cd go/src/github.com/ethereum
localhost ~/go/src/github.com/ethereum: git clone https://github.com/jpmorganchase/quorum go-ethereum
Cloning into 'go-ethereum'...
remote: Counting objects: 60237, done.
remote: Total 60237 (delta 0), reused 0 (delta 0), pack-reused 60236
Receiving objects: 100% (60237/60237), 69.61 MiB | 25.14 MiB/s, done.
Resolving deltas: 100% (41526/41526), done.
Checking connectivity... done.
localhost ~/go/src/github.com/ethereum: export GOPATH=~/go
localhost ~/go/src/github.com/ethereum: go get github.com/ethereum/go-ethereum/cmd/geth
localhost ~/go/src/github.com/ethereum: cd ~/go/bin
localhost ~/go/bin: ./geth version
Geth
Version: 1.5.0-unstable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
OS: linux
GOPATH=/home/patrick/go
GOROOT=/usr/local/go
```

-----

I can't replicate this (also on Go 1.7.3.) Are others experiencing the same issue?

(I thought it might have something to do with you being in a 'workspace' folder under home, but I failed to reproduce the issue even with the same folder structure.)

**Comment by ghost** [comment]
Hi @coeniebeyers I just `made` everything from the latest pull. Can you `env | grep GO` for us?

**Comment by coeniebeyers** [comment]
It is interesting that `geth version` reported Go Version: go1.7.3, where as a cli `$go version` reported go1.8. Changing to go1.7.3 fixed the issue, `make all` worked and I'm now able to run the tests. Apologies for the confusion, thanks for the help.

I guess atleast we know that there is an issue using go1.8

**Comment by bbrks** [comment]
I have seen this issue before when trying to build on OS X using Go 1.8 too:

```
~/go/src/github.com/jpmorganchase/quorum [master|✔]
20:42 $ go version
go version go1.8 darwin/amd64

~/go/src/github.com/jpmorganchase/quorum [master|✔]
20:42 $ make all
build/env.sh go run build/ci.go install
unexpected directory layout:
	import path: _/Users/ben/go/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/build
	root: /Users/ben/go/src/github.com/jpmorganchase/quorum/build/_workspace/src
	dir: /Users/ben/go/src/github.com/jpmorganchase/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/build
	expand root: /Users/ben/go/src/github.com/jpmorganchase/quorum/build/_workspace/src
	expand dir: /Users/ben/go/src/github.com/jpmorganchase/quorum/internal/build
	separator: /
make: *** [all] Error 1
```

**Comment by patrickmn** [comment]
Upstream: https://github.com/ethereum/go-ethereum/pull/3682

**Comment by stevenroose** [comment]
I have the same issue after upgrading to Go 1.8.

**Comment by xiaoliangsu** [comment]
Is this problem on the Mac version of Go1.8 has a solution?

**Comment by patrickmn** [comment]
Until the underlying issue is fixed, you should be able to change the path for the root Quorum repository to $GOPATH/src/github.com/ethereum/go-ethereum, then `go get github.com/ethereum/go-ethereum/cmd/geth` to install the Quorum geth binary in $GOPATH/bin.

**Comment by xiaoliangsu** [comment]
I have already change the GOPATH to my project.but when I  execute 'go install github.com/ethereum/go-ethereum ',show the following mistake.
"can't load package: package github.com/ethereum/go-ethereum: no buildable Go source files in /Users/zhangyunlong/go/src/github.com/ethereum/go-ethereum"



how can I fix it?
thank you so much

**Comment by patrickmn** [comment]
I'm sorry, that should've been `go install github.com/ethereum/go-ethereum/cmd/geth`

(Fixed the original comment as well.)

**Comment by xiaoliangsu** [comment]
thank you .but when I use the new command,I still get some mistakes.
`MacBook-Air-2:~ zhangyunlong$ cd /Users/zhangyunlong/go/src/github.com/ethereum/go-ethereum
MacBook-Air-2:go-ethereum zhangyunlong$ go install github.com/ethereum/go-ethereum/cmd/geth
/usr/local/Cellar/go/1.8.1/libexec/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:31:2: cannot find package "github.com/ethereum/ethash" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/vendor/github.com/ethereum/ethash (vendor tree)
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/ethereum/ethash (from $GOROOT)
	/Users/zhangyunlong/go/src/github.com/ethereum/ethash (from $GOPATH)
/usr/local/Cellar/go/1.8.1/libexec/src/github.com/ethereum/go-ethereum/internal/jsre/pretty.go:26:2: cannot find package "github.com/fatih/color" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/vendor/github.com/fatih/color (vendor tree)
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/fatih/color (from $GOROOT)
`
so ,what is the mistake ?
Thank you very much

**Comment by patrickmn** [comment]
Try `go get` instead of `go install` the first time (go install doesn't fetch missing dependencies.)

**Comment by xiaoliangsu** [comment]
haha,thank you sososo much!!! The question has been solved.

**Comment by xiaoliangsu** [comment]
I use the new command,it shows 
`MacBook-Air-2:~ zhangyunlong$ cd /Users/zhangyunlong/go/src/github.com/ethereum/go-ethereum
MacBook-Air-2:go-ethereum zhangyunlong$ go get github.com/ethereum/go-ethereum/cmd/geth
#github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1
../ethash/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:235: undefined: math.ReadBits
../ethash/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:236: undefined: math.ReadBits`
I guess maybe this time ,I have solved the mistake.but,when I `make geth`,I still have the mistake
`MacBook-Air-2:go-ethereum zhangyunlong$ make geth
build/env.sh go run build/ci.go install ./cmd/geth
unexpected directory layout:
	import path: _/Users/zhangyunlong/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/build
	root: /Users/zhangyunlong/go/src/github.com/ethereum/go-ethereum/build/_workspace/src
	dir: /Users/zhangyunlong/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/build
	expand root: /Users/zhangyunlong/go/src/github.com/ethereum/go-ethereum/build/_workspace/src
	expand dir: /Users/zhangyunlong/go/src/github.com/ethereum/go-ethereum/internal/build
	separator: /
make: *** [geth] Error 1`
so,that is why?
thank you so much

**Comment by patrickmn** [comment]
`make` still won't work for now, but you should be able to run either `go install github.com/ethereum/go-ethereum/cmd/geth` or `go get github.com/ethereum/go-ethereum/cmd/geth` after running the first `go get`.

(You can also just always run `go get` -- just note that if for some reason ethereum/go-ethereum isn't found in your GOPATH `go get` would re-download it from the official Ethereum repo.)

**Comment by xiaoliangsu** [comment]
before I use the command`go get github.com/ethereum/go-ethereum/cmd/geth`,the path should be changed to `$GOPATH/bin`?or` $GOPATH/src/github.com/ethereum/go-ethereum?`
I am not so sure,so I test both,after the `go get `command,it  both shows 
`MacBook-Air-2:bin zhangyunlong$ go install github.com/ethereum/go-ethereum/cmd/geth
#github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1
../src/github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:235: undefined: math.ReadBits
../src/github.com/ethereum/ethash/vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:236: undefined: math.ReadBits
MacBook-Air-2:bin zhangyunlong$ 
`
I am a little confuse,is this work now?
thank you so much.

**Comment by patrickmn** [comment]
I'm not sure what's going on there. Are you using Go 1.8?

I just tested this on Linux:

```bash
cd
mkdir -p go/src/github.com/ethereum
cd go/src/github.com/ethereum
git clone https://github.com/jpmorganchase/quorum go-ethereum
export GOPATH=~/go
go get github.com/ethereum/go-ethereum/cmd/geth
cd ~/go/bin
./geth version
```

Output:

```bash
localhost ~: cd
localhost ~: mkdir -p go/src/github.com/ethereum
localhost ~: cd go/src/github.com/ethereum
localhost ~/go/src/github.com/ethereum: git clone https://github.com/jpmorganchase/quorum go-ethereum
Cloning into 'go-ethereum'...
remote: Counting objects: 60237, done.
remote: Total 60237 (delta 0), reused 0 (delta 0), pack-reused 60236
Receiving objects: 100% (60237/60237), 69.61 MiB | 25.14 MiB/s, done.
Resolving deltas: 100% (41526/41526), done.
Checking connectivity... done.
localhost ~/go/src/github.com/ethereum: export GOPATH=~/go
localhost ~/go/src/github.com/ethereum: go get github.com/ethereum/go-ethereum/cmd/geth
localhost ~/go/src/github.com/ethereum: cd ~/go/bin
localhost ~/go/bin: ./geth version
Geth
Version: 1.5.0-unstable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
OS: linux
GOPATH=/home/patrick/go
GOROOT=/usr/local/go
```

**Comment by xiaoliangsu** [comment]
thank you sososo much, it works right now.
Thank you for your patience.Thank you for having your help.
Have a nice day.

**Comment by patrickmn** [comment]
You're absolutely welcome! Glad it worked!

I'll update my top comment to suggest that as a workaround for now.

**Comment by stevenroose** [comment]
Is this resolved?

**Comment by patrickmn** [comment]
No, @stevenroose. You're welcome to submit a pull request.

**Comment by leo-xinwang** [comment]
Pull request #137 is proposed to solve this problem.

**Comment by patrickmn** [comment]
Solved by https://github.com/jpmorganchase/quorum/pull/137. Thank you, Xin!

**Comment by timxor** [comment]
This is what worked for me!

``` sudo make all ```

**Comment by stvenyin** [comment]
i'm use go 1.8 version develop
