### ISSUE TITLE
go 1.13 on macOS gives file descriptor problem

### ISSUE THREAD

**Issue by jeffallen** [Consensys-Incorporated/quorum#889]
I understand (from Slack history, thread from Sep 7) that for the moment only Go 1.11.x is supported. This is not clearly documented, and really difficult to figure out if you naively try to follow the getting started docs (i.e. https://github.com/jpmorganchase/quorum-examples#running-locally)

On MacOS, the failing behaviour of Go 1.13 is: `Fatal: Failed to raise file descriptor allowance: invalid argument` which is very difficult to connect to the need to downgrade Go. (See also #756.)

I think it would be helpful to:
* document the Go 1.11.x limitation better
* enforce the Go 1.11.x limitation in build/env.sh, so that if you try building with go 1.13, you get a nice loud error
* use something like the code in https://github.com/dedis/onet/commit/03a8c57f6ba53d5e430bfe5a5b032b18a1093a53#diff-f7b6c3a5b64e312c20712b3c2ae51345 in order to make file descriptor setting work in MacOS again

I don't know if upstream has already solved this, or if I should be reporting it there.

**Comment by prd-fox** [comment]
Hi!

I'll add a note to the documentation stating this.

This was solved upstream in version 1.9.0.
Here is the relevant file:
https://github.com/ethereum/go-ethereum/blob/master/common/fdlimit/fdlimit_darwin.go

Once we have updated to 1.9.0 or later, I will remove the note about supported Go versions.

**Comment by magus777** [comment]
Issue still happening for me on:

go version go1.18.3 darwin/amd64
